# Generated by Django 4.1.3 on 2023-01-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("percentage_discount", "Percentage_Discount"),
                            ("flat_discount", "Flat_Discount"),
                            ("buy_one_get_one", "Buy_One_Get_One"),
                            ("free_shipping", "Free_Shipping"),
                        ],
                        max_length=100,
                    ),
                ),
                ("coupon_details", models.JSONField()),
            ],
        ),
    ]
