# Generated by Django 4.1.3 on 2023-01-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="store", name="store_owner",),
    ]
