# Generated by Django 4.1.3 on 2023-01-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0002_remove_store_store_owner"),
    ]

    operations = [
        migrations.RemoveField(model_name="store", name="store_url",),
    ]
