# Generated by Django 4.1.3 on 2023-01-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0003_remove_store_store_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="store", name="store_logo",),
    ]
