# Generated by Django 4.1.3 on 2023-01-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0004_remove_store_store_logo"),
    ]

    operations = [
        migrations.RemoveField(model_name="store", name="store_category",),
    ]
