# Generated by Django 4.1.3 on 2023-01-13 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenant", "0005_remove_store_store_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="store_category",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant.storecategory",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="store_logo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="store_owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="store_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
