# Generated by Django 4.1.3 on 2023-01-12 10:11

from django.db import migrations, models
import django.db.models.deletion
import ecom.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "SKU",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=50)),
                ("regular_price", models.FloatField()),
                ("sell_price", models.FloatField()),
                ("main_image", models.URLField(default="main_image")),
                (
                    "image_gallery",
                    models.JSONField(default=ecom.models.image_gallery_json),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[("IS", "instock"), ("OFS", "outofstock")],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("purchase_note", models.CharField(max_length=100)),
                ("minimum_order_limit", models.IntegerField()),
                ("stock_quentity", models.IntegerField()),
                ("isVisible", models.BooleanField(default=False)),
                ("views_count", models.IntegerField(default=0)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("sp", "simpleproduct"), ("vp", "variableproduct")],
                        max_length=50,
                    ),
                ),
                (
                    "product_attribute_data",
                    models.JSONField(default=ecom.models.product_attribute_data),
                ),
                ("isAffiliate", models.BooleanField(default=False)),
                ("product_discounted_price", models.FloatField()),
                ("codes", models.JSONField(default=ecom.models.codes)),
                ("product_link", models.URLField()),
                ("data_published", models.DateField(auto_now_add=True)),
                ("date_modified", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute_name", models.CharField(max_length=100)),
                ("attribute_type", models.CharField(max_length=100)),
                (
                    "values",
                    models.JSONField(default=ecom.models.product_attribute_values),
                ),
                ("default_value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("category_image", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductQueries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=999)),
                ("answer", models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=75, unique=True)),
                ("product", models.ManyToManyField(to="ecom.product")),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star_count", models.IntegerField()),
                ("review_text", models.CharField(max_length=100)),
                ("review_media", models.URLField()),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_product",
                        to="ecom.product",
                    ),
                ),
            ],
        ),
    ]
