# Generated by Django 4.1.3 on 2023-01-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_accounts", "0001_initial"),
        ("ecom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewing_customer",
                to="user_accounts.customer",
            ),
        ),
        migrations.AddField(
            model_name="productqueries",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="query_product",
                to="ecom.product",
            ),
        ),
        migrations.AddField(
            model_name="productqueries",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query_customer",
                to="user_accounts.customer",
            ),
        ),
        migrations.AddField(
            model_name="productattributes",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attributes",
                to="ecom.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecom.productcategories",
            ),
        ),
    ]
