# Generated by Django 4.1.3 on 2023-01-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupplierData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=99)),
                ("contact", models.CharField(max_length=99, unique=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("address", models.CharField(max_length=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=99)),
                ("price", models.IntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "kg"),
                            ("litre", "litre"),
                            ("millilitre", "millilitre"),
                            ("cartons", "cartons"),
                            ("metre", "metre"),
                            ("gram", "gram"),
                            ("piece", "piece"),
                            ("centimetre", "centimetre"),
                            ("feet", "feet"),
                            ("ropani", "ropani"),
                            ("aana", "squarefeet"),
                            ("squarefeet", "aana"),
                        ],
                        max_length=99,
                    ),
                ),
                ("unit_value", models.IntegerField()),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply",
                        to="inventory.supplierdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplyIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supply",
                    ),
                ),
            ],
        ),
    ]
