# Generated by Django 4.1.3 on 2023-01-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_accounts", "0001_initial"),
        ("coupon", "0001_initial"),
        ("ecom", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment_Gateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("key", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_quantity", models.IntegerField()),
                ("order_contact", models.CharField(max_length=20)),
                ("shipping_address", models.CharField(max_length=50)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("processing", "Processing"),
                            ("on_hold", "On_hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                            ("draft", "Draft"),
                        ],
                        max_length=45,
                    ),
                ),
                ("order_datetime", models.DateField(auto_now_add=True)),
                ("applied_cupons", models.CharField(max_length=100)),
                ("delivery_amount", models.FloatField(null=True)),
                ("totol_amount", models.FloatField()),
                ("grand_total", models.FloatField(null=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="coupon.coupon",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_customer",
                        to="user_accounts.customer",
                    ),
                ),
                (
                    "order_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_product",
                        to="ecom.product",
                    ),
                ),
                (
                    "payment_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.payment_gateway",
                    ),
                ),
            ],
        ),
    ]
